### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [image-charts/javascript#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by FGRibreau** [comment]
@geopic YES, I'm highly interested! Please open a PR :)

**Comment by geopic** [comment]
Very good, I'll start on it now.

**Comment by FGRibreau** [comment]
Merged :)
