### ISSUE TITLE
node_modules/image-charts/types.d.ts' is not a module.

### ISSUE THREAD

**Issue by Crymzix** [image-charts/javascript#5]
Firstly wanted to give thanks for providing such a useful service, but I'm currently running into this issue when trying to use the module with TypeScript. When trying to build my app I get this error `node_modules/image-charts/types.d.ts' is not a module.`.

I have imported the module like so: `import ImageCharts from 'image-charts'`
Not sure how to get this work, but I may have to modify `tsconfig.json` as well? Either way it's not clearly documented so I'm kind of stuck with using `const ImageCharts = require('image-charts')` in the meantime which kind of renders all the type definitions to be useless at the moment. I'll tag @geopic here since he was the one who originally implemented the `types.d.ts` declaration file.

**Comment by geopic** [comment]
Thanks for letting me know, @Crymzix. I made a small error back in September when I wrote it and will rectify this now. :+1:

**Comment by FGRibreau** [comment]
Thanks for your report @Crymzix and thanks @geopic for your fix! We've integrated this into upstream and released a new version: 5.6.3!
